General:
  Gamemodes:
    Survival: '&aSurvival'
    Creative: '&cCreative'
    Adventure: '&eAdventure'
    Spectator: '&dSpectator'
  Messages:
    No-Console: '&cSorry, but you cannot use this command via console.'
    No-Permission: '&cSorry, but you do not have permission to perform this command.'
    No-Player: '&cSorry, but we could not find this player in your current server.'
    Already-In-GM:
      Self: '&cYou are already in this gamemode!'
      Other: '&c%target% is already in this gamemode!'
Commands:
  Messages:
    Self: '&fYour gamemode has been set to %gamemode%'
    Other: "&f%target%'s gamemode has been set to %gamemode%"
  Sound:
    Enabled: true
    Type: ENTITY_EXPERIENCE_ORB_PICKUP
