author: Texxyy
name: SimpleGM
main: com.simplegm.plugin.Main
api-version: 1.18
version: ${project.version}

commands:
  gma:
    aliases: [gm2]
  gmc:
    aliases: [gm1]
  gm:
  gms:
    aliases: [gm0]
  gmsp:
    aliases: [gm3]
